name: Repology metadata

on: push
#on:
#  schedule:
#    - cron:  '* */3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Clone supplementary package repositories
      run: |
        mkdir -p /tmp/repos
        git clone --depth=1 https://github.com/termux/game-packages /tmp/repos/games
        git clone --depth=1 https://github.com/termux/science-packages /tmp/repos/science
        git clone --depth=1 https://github.com/termux/termux-root-packages /tmp/repos/root
        git clone --depth=1 https://github.com/termux/unstable-packages /tmp/repos/unstable
        git clone --depth=1 https://github.com/termux/x11-packages /tmp/repos/x11
    - name: Generate metadata
      run: |
        ./scripts/repology/generate-repology-metadata.sh ./packages/* /tmp/repos/*/packages/*
